name: Build NSIS Installer

on:
  workflow_dispatch:

jobs:
  build-installer:
    runs-on: windows-latest

    env:
      RELEASE_VERSION: 5.111
      BUCKET_NAME: github-release-files-storage
      CONDA_DIR: C:\Miniconda
      NSIS_DIR: D:\a\EcoAssist-experiments\EcoAssist-experiments\install_files\windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Nsis7z Plugin
      run: |
        curl -L -o "${{ github.workspace }}/Nsis7z_plugin.zip" "https://nsis.sourceforge.io/mediawiki/images/9/93/Nsis7z.zip"
        tar -xf "${{ github.workspace }}/Nsis7z_plugin.zip"
        7z x -o"${{ github.workspace }}/NSIS_Plugins" "${{ github.workspace }}/Nsis7z_plugin.zip"

    - name: Install Inetc Plugin
      run: |
        curl -L -o "${{ github.workspace }}/Inetc_plugin.zip" "https://nsis.sourceforge.io/mediawiki/images/c/c9/Inetc.zip"
        tar -xf "${{ github.workspace }}/Inetc_plugin.zip"
        7z x -o"${{ github.workspace }}/NSIS_Plugins" "${{ github.workspace }}/Inetc_plugin.zip"

    - name: Append VERSION to NSIS script
      run: |
        echo !define VERSION "${{ env.RELEASE_VERSION }}" > newFile.nsi
        type "D:\a\EcoAssist-experiments\EcoAssist-experiments\install_files\windows\nsis-install-compiler.nsi" >> newFile.nsi
        move /Y newFile.nsi "D:\a\EcoAssist-experiments\EcoAssist-experiments\install_files\windows\nsis-install-compiler.nsi"
      shell: cmd

    - name: Create nsis installer
      uses: joncloud/makensis-action@publish
      with:
        script-file: "${{ env.NSIS_DIR }}\nsis-install-compiler.nsi"
        additional-plugin-paths: ${{ github.workspace }}/NSIS_Plugins/Plugins

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: nsis-installer
        path: "${{ env.NSIS_DIR }}\EcoAssist-${{ env.RELEASE_VERSION }}-windows.exe"
        


    # - name: Install Inetc Plugin
    #   run: |
    #     curl -L -o Inetc.zip "https://nsis.sourceforge.io/mediawiki/images/c/c9/Inetc.zip"
    #     tar -xf Inetc.zip
    #     copy /y "Inetc\\Plugins\\amd64-unicode\\*.*" "C:\\Program Files (x86)\\NSIS\\Plugins\\"
    #     copy /y "Inetc\\Plugins\\x86-ansi\\*.*" "C:\\Program Files (x86)\\NSIS\\Plugins\\"
    #     copy /y "Inetc\\Plugins\\x86-unicode\\*.*" "C:\\Program Files (x86)\\NSIS\\Plugins\\"

    # - name: Build Installer
    #   run: |
    #     makensis installer_script.nsi

    # - name: Upload Artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: nsis-installer
    #     path: installer.exe
