name: Build NSIS Installer

on:
  workflow_dispatch:

jobs:
  build-installer:
    runs-on: windows-latest

    env:
      RELEASE_VERSION: ${{ github.event.release.tag_name }}
      BUCKET_NAME: github-release-files-storage
      CONDA_DIR: C:\Miniconda
      NSIS_SCRIPT: D:\a\EcoAssist-experiments\EcoAssist-experiments\install_files\windows\nsis-install-compiler.nsi

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Nsis7z Plugin
      run: |
        curl -L -o "${{ github.workspace }}/Nsis7z_plugin.zip" "https://nsis.sourceforge.io/mediawiki/images/9/93/Nsis7z.zip"
        tar -xf "${{ github.workspace }}/Nsis7z_plugin.zip"
        7z x -o"${{ github.workspace }}/NSIS_Plugins" "${{ github.workspace }}/Nsis7z_plugin.zip"

    # - name: Download Nsis7z plugin for NSIS
    #   uses: carlosperate/download-file-action@v1.0.3
    #   with:
    #     file-url: https://nsis.sourceforge.io/mediawiki/images/9/93/Nsis7z.zip
    #     file-name: Nsis7z_plugin.zip
    #     location: ${{ github.workspace }}

    # - name: Extract Nsis7z plugin
    #   run: 7z x -o"${{ github.workspace }}/NSIS_Plugins" "${{ github.workspace }}/Nsis7z_plugin.zip"

    - name: Install Inetc Plugin
      run: |
        curl -L -o "${{ github.workspace }}/Inetc_plugin.zip" "https://nsis.sourceforge.io/mediawiki/images/c/c9/Inetc.zip"
        tar -xf "${{ github.workspace }}/Inetc_plugin.zip"
        7z x -o"${{ github.workspace }}/NSIS_Plugins" "${{ github.workspace }}/Inetc_plugin.zip"

    # - name: Download Inetc Plugin
    #   uses: carlosperate/download-file-action@v1.0.3
    #   with:
    #     file-url: https://nsis.sourceforge.io/mediawiki/images/c/c9/Inetc.zip
    #     file-name: Inetc_plugin.zip
    #     location: D:\a\EcoAssist-experiments\EcoAssist-experiments

    # - name: Download Inetc plugin for NSIS
    #   uses: carlosperate/download-file-action@v1.0.3
    #   with:
    #     file-url: https://nsis.sourceforge.io/mediawiki/images/c/c9/Inetc.zip
    #     file-name: Inetc_plugin.zip
    #     location: ${{ github.workspace }}

    # - name: Extract Nsis7z plugin
    #   run: 7z x -o"${{ github.workspace }}/NSIS_Plugins" "${{ github.workspace }}/Inetc_plugin.zip"

    - name: Append VERSION to NSIS script
      run: |
        echo "!define VERSION `\"${{ github.event.release.tag_name }}\"`" > temp.nsi
        type "${{ env.NSIS_SCRIPT }}" >> temp.nsi
        move /Y temp.nsi "${{ env.NSIS_SCRIPT }}"

    - name: Create nsis installer
      uses: joncloud/makensis-action@publish
      with:
        script-file: "${{ env.NSIS_SCRIPT }}"
        additional-plugin-paths: ${{ github.workspace }}/NSIS_Plugins/Plugins

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: nsis-installer
        path: installer.exe
        


    # - name: Install Inetc Plugin
    #   run: |
    #     curl -L -o Inetc.zip "https://nsis.sourceforge.io/mediawiki/images/c/c9/Inetc.zip"
    #     tar -xf Inetc.zip
    #     copy /y "Inetc\\Plugins\\amd64-unicode\\*.*" "C:\\Program Files (x86)\\NSIS\\Plugins\\"
    #     copy /y "Inetc\\Plugins\\x86-ansi\\*.*" "C:\\Program Files (x86)\\NSIS\\Plugins\\"
    #     copy /y "Inetc\\Plugins\\x86-unicode\\*.*" "C:\\Program Files (x86)\\NSIS\\Plugins\\"

    # - name: Build Installer
    #   run: |
    #     makensis installer_script.nsi

    # - name: Upload Artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: nsis-installer
    #     path: installer.exe
