name: Test GCS Upload

on:
  workflow_dispatch: # Trigger manually from the Actions tab
  # push:
  #   branches:
  #     - main  # Trigger on pushes to the main branch

jobs:
  test_upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v3

    - name: Clone a public GitHub repository
      run: |
        git clone https://github.com/octocat/hello-world.git
        echo "Repository cloned!"

    - name: Zip the cloned repository
      run: |
        zip -r osx-arm-v5.21.zip hello-world/
        echo "Repository zipped!"

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLE_STORAGE_UPLOAD_KEY }}  # Your secret for the service account JSON key

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: github-file-storage

    - name: Upload file to GCS (replacing any old files)
      run: |
        FOLDER_NAME="v5.21"
        BUCKET_NAME="github-release-files-storage"
        FILE_NAME="osx-arm-v5.21.zip"

        echo "Uploading $FILE_NAME to /$FOLDER_NAME/ in bucket $BUCKET_NAME"
        
        # Ensure the folder exists by creating a null object
        gsutil -q stat gs://$BUCKET_NAME/$FOLDER_NAME/ || gsutil cp /dev/null gs://$BUCKET_NAME/$FOLDER_NAME/

        # Upload the file, overwriting any existing file with the same name
        gsutil cp -r $FILE_NAME gs://$BUCKET_NAME/$FOLDER_NAME/
        echo "File uploaded to GCS at gs://$BUCKET_NAME/$FOLDER_NAME/$FILE_NAME"

        # Form the public URL
        PUBLIC_URL="https://storage.googleapis.com/$BUCKET_NAME/$FOLDER_NAME/$FILE_NAME"
        echo "File is publicly accessible at: $PUBLIC_URL"
