name: Test GCS Upload

on:
  workflow_dispatch: # Trigger manually from the Actions tab
  # push:
  #   branches:
  #     - main  # Trigger on pushes to the main branch

jobs:
  test_upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v3

    - name: Clone a public GitHub repository
      run: |
        git clone https://github.com/octocat/hello-world.git
        echo "Repository cloned!"

    - name: Zip the cloned repository
      run: |
        zip -r osx-arm-v5.21.zip hello-world/
        echo "Repository zipped!"

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLE_STORAGE_UPLOAD_KEY }}  # Your secret for the service account JSON key

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: github-file-storage

    - name: Create folder in GCS (if not exists) and upload zip
      run: |
        FOLDER_NAME="v5.21/"
        BUCKET_NAME="github-release-files-storage"

        # Create a folder-like object in GCS
        echo "Ensuring folder $FOLDER_NAME exists in bucket $BUCKET_NAME"
        gsutil -q stat gs://$BUCKET_NAME/$FOLDER_NAME || gsutil cp /dev/null gs://$BUCKET_NAME/$FOLDER_NAME

        # Upload the zip file to the folder
        echo "Uploading file to $FOLDER_NAME"
        gsutil cp osx-arm-v5.21.zip gs://$BUCKET_NAME/$FOLDER_NAME
        echo "File uploaded to GCS at gs://$BUCKET_NAME/$FOLDER_NAME"

        # Delete the null object representing the folder
        echo "Cleaning up null object for folder $FOLDER_NAME in bucket $BUCKET_NAME"
        gsutil rm gs://$BUCKET_NAME/$FOLDER_NAME
        echo "Null object removed from GCS!"
